[[constraint]]
  name = "github.com/fatih/color"
  version = "1.5.0"

[[constraint]]
  name = "github.com/mattn/go-isatty"
  version = "0.0.3"

[[constraint]]
  branch = "master"
  name = "github.com/motki/core"

[[constraint]]
  branch = "master"
  name = "github.com/peterh/liner"

[[constraint]]
  branch = "master"
  name = "github.com/shopspring/decimal"
